In [20]:
import numpy as np

def f(x):
    return x[0]+x[1]-(x[2]+x[3])+x[4]+x[5]-(x[6]+x[7])
# 
# def croiser(x1,x2):
#     index = np.random.randint(len(x1))
#     for i in range(index, len(x1)):
#         x1[i], x2[i] = x2[i], x1[i]


def croiser(X):
    i, j = np.random.choice(len(X), size=2, replace=False)
    index = np.random.randint(len(X[0]))
    f1 = X[i]  #fis 1
    f2 = X[j]  #fis 2
    for k in range(index, len(X[0])):
        f2[k], f1[k] = X[i][k], X[j][k]
    X.append(f1)
    return f1, f2


def mutation(x):
    rand_index = np.random.randint(len(x))
    x[rand_index] = np.random.randint(0, 10)




In [21]:
X = []

for i in range(4):
     X.append(np.random.randint(1,9,size=8))
X

[array([8, 4, 1, 5, 2, 1, 4, 6]),
 array([8, 6, 4, 8, 1, 7, 8, 6]),
 array([5, 2, 8, 1, 6, 7, 5, 5]),
 array([7, 3, 5, 6, 8, 6, 1, 3])]

In [22]:
fX = [f(x) for x in X]
fX

[-1, -4, 1, 9]

In [23]:
# Sort X based on fX
X_sorted = [x for _, x in sorted(zip(fX, X),reverse=True ,key=lambda pair: pair[0])]

X_sorted

[array([7, 3, 5, 6, 8, 6, 1, 3]),
 array([5, 2, 8, 1, 6, 7, 5, 5]),
 array([8, 4, 1, 5, 2, 1, 4, 6]),
 array([8, 6, 4, 8, 1, 7, 8, 6])]

In [24]:
fX_sorted = [f(x) for x in X_sorted]
fX_sorted


[9, 1, -1, -4]

In [25]:
# croiser(X_sorted[0],X_sorted[1])
# croiser(X_sorted[1],X_sorted[2])
# croiser(X_sorted[0], X_sorted[2])
# for j in range(np.random.randint(8)):
#     croiser(X_sorted[0], X_sorted[3])
# X_sorted
# X_sorted
croiser(X_sorted)

(array([8, 6, 4, 8, 1, 7, 8, 6]), array([7, 3, 5, 6, 8, 6, 1, 3]))

In [26]:
fX_sorted = [f(x) for x in X_sorted]
fX_sorted

[-4, 1, -1, 9, -4]