In [67]:
import numpy as np

def f(x):
    return x[0]+x[1]-(x[2]+x[3])+x[4]+x[5]-(x[6]+x[7])

def croiser(X):
    i,j = np.random.choice(len(X),size=2,replace=False)
    index = np.random.randint(len(X[0]))
    f1 = X[i]   #fis 1
    f2 = X[j]   #fis 2
    for k in range(index, len(X[0])):
        f2[k], f1[k] = X[i][k], X[j][k]
    return f1,f2

def mutation(x):
    rand_index = np.random.randint(len(x))
    x[rand_index] = np.random.randint(0,10)



In [68]:

X = []
for i in range(4):
     X.append(np.random.randint(0,10,size=8))
X

[array([0, 0, 4, 7, 6, 8, 1, 0]),
 array([6, 1, 0, 7, 8, 9, 7, 9]),
 array([6, 8, 1, 9, 1, 6, 6, 3]),
 array([5, 1, 4, 8, 4, 9, 4, 1])]

In [69]:
fX = [f(x) for x in X]
fX

[2, 1, 2, 2]

In [70]:
# Sort X based on fX
X_sorted = [x for _, x in sorted(zip(fX, X),reverse=True ,key=lambda pair: pair[0])]

X_sorted

[array([0, 0, 4, 7, 6, 8, 1, 0]),
 array([6, 8, 1, 9, 1, 6, 6, 3]),
 array([5, 1, 4, 8, 4, 9, 4, 1]),
 array([6, 1, 0, 7, 8, 9, 7, 9])]

In [71]:
fX_sorted = [f(x) for x in X_sorted]
fX_sorted


[2, 2, 2, 1]

In [72]:
croiser(X_sorted[0],X_sorted[1])
croiser(X_sorted[1],X_sorted[2])
croiser(X_sorted[0], X_sorted[2])
for j in range(np.random.randint(8)):
    croiser(X_sorted[0], X_sorted[3])
X_sorted
X_sorted 

[array([0, 1, 0, 7, 6, 9, 7, 9]),
 array([5, 1, 4, 8, 4, 9, 4, 1]),
 array([6, 8, 1, 7, 1, 6, 6, 3]),
 array([6, 0, 4, 9, 8, 8, 1, 0])]

In [73]:
fX_sorted = [f(x) for x in X_sorted]
fX_sorted

[-7, 2, 4, 8]