In [53]:
import numpy as np

def f(x):
    return x[0]+x[1]-(x[2]+x[3])+x[4]+x[5]-(x[6]+x[7])

def croiser(x1,x2):
    index = np.random.randint(len(x1))
    for i in range(index, len(x1)):
        x1[i], x2[i] = x2[i], x1[i]
        
X = []

for i in range(4):
     X.append(np.random.randint(1,9,size=8))
X

[array([4, 2, 1, 6, 5, 3, 7, 6]),
 array([2, 8, 3, 6, 4, 2, 7, 6]),
 array([7, 4, 4, 8, 3, 8, 5, 8]),
 array([5, 4, 6, 2, 6, 6, 8, 4])]

In [54]:
fX = [f(x) for x in X]
fX

[-6, -6, -3, 1]

In [55]:
# Sort X based on fX
X_sorted = [x for _, x in sorted(zip(fX, X),reverse=True ,key=lambda pair: pair[0])]

X_sorted

[array([5, 4, 6, 2, 6, 6, 8, 4]),
 array([7, 4, 4, 8, 3, 8, 5, 8]),
 array([4, 2, 1, 6, 5, 3, 7, 6]),
 array([2, 8, 3, 6, 4, 2, 7, 6])]

In [56]:
fX_sorted = [f(x) for x in X_sorted]
fX_sorted


[1, -3, -6, -6]

In [57]:
croiser(X_sorted[0],X_sorted[1])
croiser(X_sorted[1],X_sorted[2])
croiser(X_sorted[0], X_sorted[2])
for j in range(np.random.randint(8)):
    croiser(X_sorted[0], X_sorted[3])
X_sorted
X_sorted

[array([2, 8, 3, 6, 5, 8, 8, 4]),
 array([7, 4, 4, 8, 3, 3, 7, 6]),
 array([5, 4, 6, 2, 6, 6, 5, 8]),
 array([4, 2, 1, 6, 4, 2, 7, 6])]

In [58]:
fX_sorted = [f(x) for x in X_sorted]
fX_sorted

[2, -8, 0, -8]